This implementation is incomplete. There is still a need to identify when a user has won as well as update the masked board. 

# Approach

1/ Code a Minesweeper game

2/ Take any board length (the board is square usually) and number of mines

3/ Take user input as x, y coordinates

4/ End the game if they click a mine, reveal the bordering numbers if they click somewhere else.

5/ If the user clicks on a square with “zero”, the board propagates to the reveal all consecutive 0's as a convenience method

In [116]:
import numpy as np
import random

methods required:
- initialize board
    - store locations of the mines
- get bomb tallies for each coordinate 
- user input
    - reveal tallies of all adjacent coordinates
    - have checks for if user clicks on mine
    - if valid tile, the all adjacent blocks are revealed

In [176]:
class Minesweeper():
    def __init__(self,board_length,n_mines):
        self.board_length,self.n_mines = board_length, n_mines
        self.board = np.array(self.init_board(self.board_length,self.n_mines))
        self.mask = np.array([[True for _ in range(board_length)] for _ in range(board_length)])
        
    def init_board(self, board_length,n_mines):
        """
        -1 = bomb
        N = any other number if the number of bombs adjacent to tile
        """
        # initiating the board with all zeroes
        board = [[0 for _ in range(board_length)] for _ in range(board_length)]
        
        # populating all the mine locations
        mine_locations = set()
        while len(mine_locations) <= n_mines:
            for x in range(n_mines):
                mine_locations.add((random.randint(0,board_length-1),random.randint(0,board_length-1)))
        
        for x,y in mine_locations:
            board[x][y] = -1
        
        # update board with all the bomb totals
        for row in range(len(board)):
            for col in range(len(board[row])):
                if board[row][col] != -1: 
                    nums = [self.get_value(board,x,y) for (x,y) in \
                        [(row-1,col),(row,col+1),(row,col-1),(row,col+1),(row+1,col+1),(row-1,col-1)]]
                    board[row][col] = abs(sum([num for num in nums if num == -1]))

        return board
    
            
    def get_value(self,board,x,y):
        if 0 <= x < self.board_length and 0 <= y < self.board_length:
            return board[x][y]
        else:
            return 0
        
    def process_user_input(self,x,y):
        if self.board[x][y] == -1: 
            return True
        else: 
            self.mask[x][y] == 1
            # reveal tallies of adjacent mines
    
    def get_printable_board(self):
        # return the masked board back to the user
        return (np.ma.array(self.board, mask=self.mask, fill_value=0)).filled()
    
    
    def play(self):
        print("Welcome to minesweeper!")
        while True:
            print(self.get_printable_board())
            inp = input("Please enter the coordinates e.g. 1 2 of your next move:  ")
            x,y = [int(i) for i in inp.split()]
            if self.process_user_input(x,y): break
        
        print(self.get_printable_board())
        print("Game over!")

In [177]:
x = np.ma.array([1,2,3,4,5], mask=[0,0,1,0,1], fill_value=0)
x.filled()
# array([   1,    2, -999,    4, -999])
x.filled(fill_value=1000)
# array([   1,    2, 1000,    4, 1000])
x.filled()

array([1, 2, 0, 4, 0])

In [178]:
m = Minesweeper(10,50)

In [179]:
m.play()

Welcome to minesweeper!
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Please enter the coordinates e.g. 1 2 of your next move:  3 4
Game over!


In [166]:
if __name__ == "__main__":
    game = Minesweeper(5,10):
    game.play()

SyntaxError: invalid syntax (<ipython-input-166-cb21d9b20c00>, line 2)