# Implementation

In [263]:
import numpy as np
class LinearRegression:
    def __init__(self):
        pass
    
    @staticmethod
    def add_bias_parameter(x):
        return np.concatenate([np.ones((len(x),1)),x],axis=1)
    
    def fit(self,x,y):
        self.x = self.add_bias_parameter(x)
        self.y = y
        t = self.x.transpose()
        self.theta = (np.linalg.inv((t@self.x))@t)@self.y
    
    def predict(self,x):
        x = self.add_bias_parameter(x)
        return x @ self.theta
        

In [308]:
def rmse(a,p):
    return np.sqrt(((a-p)**2).mean())

## Random Data with Constant Y

In [309]:
from sklearn.model_selection import train_test_split

X,y = np.random.randn(400,2),np.random.randint(low=5,high=6,size=(400))

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)

In [310]:
model = LinearRegression()
model.fit(X_train,y_train)

In [311]:
X_test.shape

(100, 2)

In [312]:
preds = model.predict(X_test)

In [313]:
rmse(y_test,preds) # should be close to 0

0.0

## Boston Dataset

In [314]:
from sklearn.datasets import load_boston

In [315]:
X,y = load_boston(return_X_y=True)

In [316]:
X.shape,y.shape

((506, 13), (506,))

In [317]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)

In [318]:
model = LinearRegression()

In [319]:
model.fit(X_train,y_train)

In [320]:
model.theta

array([ 2.98364202e+01, -1.28322638e-01,  2.95517751e-02,  4.88590934e-02,
        2.77350326e+00, -1.62388292e+01,  4.36875476e+00, -9.24808158e-03,
       -1.40086668e+00,  2.57761243e-01, -9.95694820e-03, -9.23122944e-01,
        1.31854199e-02, -5.17639519e-01])

In [321]:
preds = model.predict(X_test)

In [322]:
# baseline rmse
m = y_train.mean()
mean_preds = np.array([m for _ in range(len(y_test))])
rmse(y_test,mean_preds)

8.500633082280295

In [323]:
# model rmse
rmse(y_test,preds)

4.700924890603999

In [324]:
y_test.std()

8.368222251726307

In [325]:
y_test

array([23.6, 32.4, 13.6, 22.8, 16.1, 20. , 17.8, 14. , 19.6, 16.8, 21.5,
       18.9,  7. , 21.2, 18.5, 29.8, 18.8, 10.2, 50. , 14.1, 25.2, 29.1,
       12.7, 22.4, 14.2, 13.8, 20.3, 14.9, 21.7, 18.3, 23.1, 23.8, 15. ,
       20.8, 19.1, 19.4, 34.7, 19.5, 24.4, 23.4, 19.7, 28.2, 50. , 17.4,
       22.6, 15.1, 13.1, 24.2, 19.9, 24. , 18.9, 35.4, 15.2, 26.5, 43.5,
       21.2, 18.4, 28.5, 23.9, 18.5, 25. , 35.4, 31.5, 20.2, 24.1, 20. ,
       13.1, 24.8, 30.8, 12.7, 20. , 23.7, 10.8, 20.6, 20.8,  5. , 20.1,
       48.5, 10.9,  7. , 20.9, 17.2, 20.9,  9.7, 19.4, 29. , 16.4, 25. ,
       25. , 17.1, 23.2, 10.4, 19.6, 17.2, 27.5, 23. , 50. , 17.9,  9.6,
       17.2, 22.5, 21.4, 12. , 19.9, 19.4, 13.4, 18.2, 24.6, 21.1, 24.7,
        8.7, 27.5, 20.7, 36.2, 31.6, 11.7, 39.8, 13.9, 21.8, 23.7, 17.6,
       24.4,  8.8, 19.2, 25.3, 20.4, 23.1])

In [326]:
model.theta

array([ 2.98364202e+01, -1.28322638e-01,  2.95517751e-02,  4.88590934e-02,
        2.77350326e+00, -1.62388292e+01,  4.36875476e+00, -9.24808158e-03,
       -1.40086668e+00,  2.57761243e-01, -9.95694820e-03, -9.23122944e-01,
        1.31854199e-02, -5.17639519e-01])

### Comparison to Stats Models

https://datascienceplus.com/linear-regression-from-scratch-in-python/

In [327]:
import pandas as pd
results = pd.DataFrame({'my_coeffs':model.theta}, index=list(range(len(model.theta))))

In [328]:
from statsmodels.regression.linear_model import OLS
coeffs_lm = OLS(y_train, model.add_bias_parameter(X_train)).fit().params

In [329]:
results["sm_coeffs"] = coeffs_lm

In [330]:
results # coefs are exactly the same!

my_coeffs  sm_coeffs
0   29.836420  29.836420
1   -0.128323  -0.128323
2    0.029552   0.029552
3    0.048859   0.048859
4    2.773503   2.773503
5  -16.238829 -16.238829
6    4.368755   4.368755
7   -0.009248  -0.009248
8   -1.400867  -1.400867
9    0.257761   0.257761
10  -0.009957  -0.009957
11  -0.923123  -0.923123
12   0.013185   0.013185
13  -0.517640  -0.517640