# Implementation

In [2]:
import numpy as np
class LinearRegression:
    def __init__(self):
        pass
    
    @staticmethod
    def add_bias_parameter(x):
        return np.concatenate([np.ones((len(x),1)),x],axis=1)
    
    def fit(self,x,y):
        self.x = self.add_bias_parameter(x)
        self.y = y
        t = self.x.transpose()
        self.theta = (np.linalg.inv((t@self.x))@t)@self.y
    
    def predict(self,x):
        x = self.add_bias_parameter(x)
        return x @ self.theta
        

In [3]:
def rmse(a,p):
    return np.sqrt(((a-p)**2).mean())

## Random Data with Constant Y

In [4]:
from sklearn.model_selection import train_test_split

X,y = np.random.randn(400,2),np.random.randint(low=5,high=6,size=(400))

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)

In [5]:
model = LinearRegression()
model.fit(X_train,y_train)

In [6]:
X_test.shape

(100, 2)

In [7]:
preds = model.predict(X_test)

In [8]:
rmse(y_test,preds) # should be close to 0

0.0

## Boston Dataset

In [9]:
from sklearn.datasets import load_boston
from sklearn.preprocessing import StandardScaler


In [10]:
X,y = load_boston(return_X_y=True)

In [11]:
X.shape,y.shape

((506, 13), (506,))

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)
scl = StandardScaler()
X_train = scl.fit_transform(X_train)
X_test = scl.transform(X_test)

In [14]:
model = LinearRegression()

In [15]:
model.fit(X_train,y_train)

In [16]:
model.theta

array([22.90791557, -1.06546379,  0.68154987,  0.33928836,  0.73726309,
       -1.93178062,  3.14172655, -0.25586276, -2.95561026,  2.21416067,
       -1.65127265, -2.08714915,  1.15235744, -3.69504236])

In [17]:
preds = model.predict(X_test)

In [18]:
# baseline rmse
m = y_train.mean()
mean_preds = np.array([m for _ in range(len(y_test))])
rmse(y_test,mean_preds)

8.500633082280295

In [19]:
# model rmse
rmse(y_test,preds)

4.700924890603765

In [22]:
y_test.std()

8.368222251726307

In [23]:
y_test

array([23.6, 32.4, 13.6, 22.8, 16.1, 20. , 17.8, 14. , 19.6, 16.8, 21.5,
       18.9,  7. , 21.2, 18.5, 29.8, 18.8, 10.2, 50. , 14.1, 25.2, 29.1,
       12.7, 22.4, 14.2, 13.8, 20.3, 14.9, 21.7, 18.3, 23.1, 23.8, 15. ,
       20.8, 19.1, 19.4, 34.7, 19.5, 24.4, 23.4, 19.7, 28.2, 50. , 17.4,
       22.6, 15.1, 13.1, 24.2, 19.9, 24. , 18.9, 35.4, 15.2, 26.5, 43.5,
       21.2, 18.4, 28.5, 23.9, 18.5, 25. , 35.4, 31.5, 20.2, 24.1, 20. ,
       13.1, 24.8, 30.8, 12.7, 20. , 23.7, 10.8, 20.6, 20.8,  5. , 20.1,
       48.5, 10.9,  7. , 20.9, 17.2, 20.9,  9.7, 19.4, 29. , 16.4, 25. ,
       25. , 17.1, 23.2, 10.4, 19.6, 17.2, 27.5, 23. , 50. , 17.9,  9.6,
       17.2, 22.5, 21.4, 12. , 19.9, 19.4, 13.4, 18.2, 24.6, 21.1, 24.7,
        8.7, 27.5, 20.7, 36.2, 31.6, 11.7, 39.8, 13.9, 21.8, 23.7, 17.6,
       24.4,  8.8, 19.2, 25.3, 20.4, 23.1])

In [24]:
model.theta

array([22.90791557, -1.06546379,  0.68154987,  0.33928836,  0.73726309,
       -1.93178062,  3.14172655, -0.25586276, -2.95561026,  2.21416067,
       -1.65127265, -2.08714915,  1.15235744, -3.69504236])

### Comparison to Stats Models

https://datascienceplus.com/linear-regression-from-scratch-in-python/

In [25]:
import pandas as pd
results = pd.DataFrame({'my_coeffs':model.theta}, index=list(range(len(model.theta))))

In [26]:
from statsmodels.regression.linear_model import OLS
coeffs_lm = OLS(y_train, model.add_bias_parameter(X_train)).fit().params

In [27]:
results["sm_coeffs"] = coeffs_lm

In [28]:
results # coefs are exactly the same!

my_coeffs  sm_coeffs
0   22.907916  22.907916
1   -1.065464  -1.065464
2    0.681550   0.681550
3    0.339288   0.339288
4    0.737263   0.737263
5   -1.931781  -1.931781
6    3.141727   3.141727
7   -0.255863  -0.255863
8   -2.955610  -2.955610
9    2.214161   2.214161
10  -1.651273  -1.651273
11  -2.087149  -2.087149
12   1.152357   1.152357
13  -3.695042  -3.695042